### ISSUE TITLE
Invariant Violation: requireNativeComponent: "RNMaterialLetterIcon" was not found in the UIManager.

### ISSUE THREAD

**Issue by Seunope** [gaetanozappi/react-native-navigation-drawer-layout#1]
react-native init TestDrawer

npm i react-native-navigation-drawer-layout
 
i copied the content found in  [package documentation](https://www.npmjs.com/package/react-native-navigation-drawer-layout) to my App.js

package.json looks like this

```
{
...
  "dependencies": {
    "react": "16.6.1",
    "react-native": "0.57.7",
    "react-native-navigation-drawer-layout": "0.0.3"
  },
  "devDependencies": {
    "babel-jest": "23.6.0",
    "jest": "23.6.0",
    "metro-react-native-babel-preset": "0.49.2",
    "react-test-renderer": "16.6.1"
  },
...
}
```
I ran 

npm react-native run-android 
 I got this error

>Invariant Violation: Invariant Violation: requireNativeComponent: "RNMaterialLetterIcon" was not found in the UIManager.

![capture](https://user-images.githubusercontent.com/6086663/49219163-c8106700-f3d2-11e8-9842-e50b56b3f55f.PNG)

**Comment by gaetanozappi** [comment]
Hi @Seunope , 
take a look here: https://github.com/gaetanozappi/react-native-navigation-drawer-layout#-getting-started
This should solve the problem.

Let me know if this does not solve it.

P.S.
For documentation and for the use of the props, use the one found here on github, it is the updated version.

Soon I will release a new version on npm.

**Comment by Seunope** [comment]
@gaetanozappi This fix, worked like charm. Lots of download (gradle & react-native-material-letter-icon ) happened at the background!

I appreciate all the effort you put into this. Thanks!

**Comment by ghost** [comment]
how to fix ???

**Comment by gaetanozappi** [comment]
@bestkung1  : What the problem, could you be specific?
