### ISSUE TITLE
How do we trigger this drawe? 

### ISSUE THREAD

**Issue by jelordreygulle** [gaetanozappi/react-native-navigation-drawer-layout#2]
How can we trigger this drawer for example I wanted to use it as a sidebar and then trigger in on my Home when user swipe or click the menu button. Thank You.

**Comment by gaetanozappi** [comment]
Hi @jelordreygulle ,
Try it so give the module the following ref:
```
<NavigationDrawerLayout
ref = {_ drawer => (this.drawer = _drawer)}
.... />
```

To open and close the drawer at the click of a button, you can do this:

```
          <Button
            onPress={()=>this.drawer.openDrawer()}
            title="Open"
            color="#4286f4"
          />
          <Button
            onPress={()=>this.drawer.closeDrawer()}
            title="Close"
            color="#34ed6b"
          />
```

For the swipe, for example the opening just make the gesture, a movement from the left to the right or the contrary depending on how you set the menu: `drawerPosition = "left"`
For closing, the opposite movement or just click on the part where the menu is not found, ie the opaque part.

P.S.
Consider one thing, currently the menu opens automatically, then at the opening of the app.

I hope I have correctly understood your question.
Let me know if this does not solve it.

**Comment by jelordreygulle** [comment]
Sir, do you have an existing implementation project of this?

**Comment by jelordreygulle** [comment]
<Button
            onPress={()=>this.drawer.openDrawer()}
            title="Open"
            color="#4286f4"
          /> i did try this but it resulted to underfined is not an onject (evaluating this.drawer.openDrawer?

**Comment by gaetanozappi** [comment]
@jelordreygulle : Can you publish all the code you are using?

**Comment by jelordreygulle** [comment]
yeah I can.

**Comment by jelordreygulle** [comment]
Also Sir , can you please create an example on how to use that layout?

**Comment by jelordreygulle** [comment]
@gaetanozappi  Are you still there?  , I'm not familiar with your scaffold by the way, that is why.

**Comment by jelordreygulle** [comment]
Just a template , Thank you.

**Comment by jelordreygulle** [comment]
@gaetanozappi  Do you want to see the code?

**Comment by jelordreygulle** [comment]
Also @gaetanozappi  where there is another white drawer below it? why there were 2 drawers?

**Comment by jelordreygulle** [comment]
@gaetanozappi  what do you mean by this ? <NavigationDrawerLayout
ref = {_ drawer => (this.drawer = _drawer)}
.... />

**Comment by gaetanozappi** [comment]
@jelordreygulle : I would ask you not to write many messages, but to always change last posted by you.

I tried to create a basic example just for you: https://snack.expo.io/rJBCZxHgE

The example I created on expo is not the version you find by downloading the module `react-native-navigation-drawer-layout`, because the native modules do not work on expo, as you can see the account icons do not appear, but it gives you a generic view of how the module works.

Consider spending some time to get yourself an example with a few pages.
Please study it carefully and read the documentation I wrote on the module.

If the example does not work let me know.

**Comment by jelordreygulle** [comment]
Thank You Sir.

**Comment by jelordreygulle** [comment]
Also Sir , I would just like to recommend that it would be good if menu will close when afternavigating to a page.

**Comment by gaetanozappi** [comment]
The menu can be closed, just put the attribute: `close: true`
example see:

```
{
            type: 'menu',
            name: 'opt14',
            title: 'Close Drawer',
            icon: 'exit-to-app',
            colorText: '#000',
            colorTextFocus: '#607D8B',
            colorIcon: '#c1c1c1',
            colorIconFocus: '#607D8B',
            background: 'transparent',
            backgroundFocus: '#e8e8e8',
            close: true,
},
```

In the example I posted you before there is integrated and in the documentation you find it in `Menu type menu`.

**Comment by jelordreygulle** [comment]
It did work using        onPress={() => this.props.navigation.openDrawer()} , but how can we remove the white background page which is seen below the menu? there were 2 side menu that goes out.

**Comment by jelordreygulle** [comment]
"The menu can be closed, just put the attribute: close: true " What i mean Sir is that when i go to i click home or navigate to home then menu will close. so i can see the whole home page. Automatic close when i navigate.

**Comment by jelordreygulle** [comment]
Thank you for this. I'll just be posting query regarding any suggestions and questions. such a great help

**Comment by gaetanozappi** [comment]
@jelordreygulle :    If the problem has been solved please kindly close the thread.
