### ISSUE TITLE
Using local images

### ISSUE THREAD

**Issue by yulioaj290** [gaetanozappi/react-native-navigation-drawer-layout#5]
Hi. 
Your usage example and the implementation of the `NavigationDrawerLayout` file are using an implementation of the `ImageBackground` component with images from network (not local).

I need to load the images locally for testing purposes, How can I do it?

The implementation of the `NavigationDrawerLayout.js` is as follow:

```
 <ImageBackground
     source={{
          uri: imageBackground,
     }}
     ...>
...
 </ImageBackground>
```

Can you change the implementation of this in order to use local images? Or
May I do a Pull Request to improve this code?

**Comment by gaetanozappi** [comment]
Hi @yulioaj290 , 

I have uploaded version `0.0.7` as requested.
In order to use local images, you have to do this:

```
<NavigationDrawerLayout
        ...
        imageBackground={require('../assets/imageBackground.png')}
        ...
```

Let me know if there are any problems or if it doesn't work properly.

**Comment by gaetanozappi** [comment]
Hi @yulioaj290 , 

I have uploaded version `0.0.7` as requested.
In order to use local images, you have to do this:

```
<NavigationDrawerLayout
        ...
        imageBackground={require('../assets/imageBackground.png')}
        ...
```

Let me know if there are any problems or if it doesn't work properly.

I would like to ask you to respect the documentation I wrote with commitment to the issues.
You can do all the pr you want.

**Comment by yulioaj290** [comment]
Hi @gaetanozappi
Thank you for the quick response and for uploading the new version. It works great!
I apologize to not respect the issues documentation. :(

PS: I write another issue related to this on [react-native-avatar-social#1](https://github.com/gaetanozappi/react-native-avatar-social/issues/1#issue-465884151)
